[package]
name = "rmf_sandbox"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "librmf_sandbox"

[[bin]]
path = "src/main.rs"
name = "rmf_sandbox"

[dependencies]
bevy = "0.7"
rand = "0.8.5"
bevy_egui = "0.13"
serde_yaml = "0.8.23"
wasm-bindgen = "0.2"
web-sys = { version = "0.3.56", features = ["console"] }
yaml-rust = "0.4"
